### ISSUE TITLE
help with coverage.py

### ISSUE THREAD

**Issue by danknight** [tinybio/filter_contigs#1]
Hello,

I have a spades generated assembly file (.fasta) that I am trying to trim for both length and coverage. 

I have successfully run the script for length Filter_length.py but the filter_coverage script is just not working, the output is always a blank fasta file no matter the coverage number provided 
e.g.

./filter_coverage.py 1 ./fasta.file
./filter_coverage.py 2 ./fasta.file
./filter_coverage.py 5 ./fasta.file

I can see there are definitely contigs with coverage that should be trimmed. 

Any ideas?
Thanks in advance
Dan

**Comment by crashfrog** [comment]
Hi Dan,

Found a bug in the assembly header-matching regex that was preventing any header from matching. Try the new version, it should work.

Justin

**Comment by crashfrog** [comment]
should be fixed in most recent commit.
